### ISSUE TITLE
Fix unhandled promise rejection

### ISSUE THREAD

**Issue by FlorentTorregrosa** [drupal-composer/drupal-l10n#39]
On:
* PHP 8.1.26
* Composer version 2.6.6 2023-12-08 18:32:26
* drupal-composer/drupal-l10n: 2.0.3

When a translation file does not exist:
```
Unhandled promise rejection with Composer\Downloader\TransportException: The "https://ftp.drupal.org/files/translations/all/webform/webform-8.x-6.2.fr.po" file could not be downloaded (HTTP/2 404 ) in phar:///usr/bin/composer/src/Composer/Util/Http/CurlDownloader.php:630
Stack trace:
#0 phar:///usr/bin/composer/src/Composer/Util/Http/CurlDownloader.php(442): Composer\Util\Http\CurlDownloader->failResponse(Array, Object(Composer\Util\Http\CurlResponse), 'HTTP/2 404 ')
#1 phar:///usr/bin/composer/src/Composer/Util/HttpDownloader.php(392): Composer\Util\Http\CurlDownloader->tick()
#2 phar:///usr/bin/composer/src/Composer/Util/HttpDownloader.php(363): Composer\Util\HttpDownloader->countActiveJobs(58)
#3 phar:///usr/bin/composer/src/Composer/Util/HttpDownloader.php(157): Composer\Util\HttpDownloader->wait(58)
#4 /project/vendor/drupal-composer/drupal-l10n/src/FileFetcher.php(107): Composer\Util\HttpDownloader->copy('https://ftp.dru...', '/project/app/tr...')
#5 /project/vendor/drupal-composer/drupal-l10n/src/Handler.php(179): DrupalComposer\DrupalL10n\FileFetcher->fetch(Array, '/project/app/tr...')
#6 /project/vendor/drupal-composer/drupal-l10n/src/DrupalL10nCommand.php(35): DrupalComposer\DrupalL10n\Handler->downloadLocalization(true)
#7 phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php(298): DrupalComposer\DrupalL10n\DrupalL10nCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///usr/bin/composer/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///usr/bin/composer/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(DrupalComposer\DrupalL10n\DrupalL10nCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///usr/bin/composer/src/Composer/Console/Application.php(382): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///usr/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///usr/bin/composer/src/Composer/Console/Application.php(145): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar:///usr/bin/composer/bin/composer(93): Composer\Console\Application->run()
#14 /usr/bin/composer(29): require('phar:///usr/bin...')
#15 {main}
```

Not sure if this from a Composer update or a Drupal.org server configuration update.

**Comment by FlorentTorregrosa** [comment]
Coming from newer Composer version.
